# Generated by Django 5.2.16 on 2026-07-23 16:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Racer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(max_length=36, unique=True)),
                ('sprite_key', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='#f6c453', max_length=7)),
                ('base_speed', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(1.5)])),
                ('resilience', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('recovery', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('aggression', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('chaos', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('default_odds', models.DecimalField(decimal_places=2, default=Decimal('4.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.01')), django.core.validators.MaxValueValidator(Decimal('99.99'))])),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoomSettings',
            fields=[
                ('singleton', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='To The Races', max_length=60)),
                ('is_paused', models.BooleanField(default=False)),
                ('betting_seconds', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(300)])),
                ('lineup_seconds', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('race_seconds', models.PositiveSmallIntegerField(default=25, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('results_seconds', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(120)])),
                ('opening_balance_cents', models.PositiveBigIntegerField(default=10000)),
                ('max_round_stake_cents', models.PositiveBigIntegerField(default=10000)),
                ('runner_count', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('state', models.CharField(choices=[('open', 'Betting open'), ('locked', 'Betting locked'), ('racing', 'Race in progress'), ('results', 'Showing results')], default='open', max_length=10)),
                ('opened_at', models.DateTimeField()),
                ('locks_at', models.DateTimeField()),
                ('race_starts_at', models.DateTimeField()),
                ('race_ends_at', models.DateTimeField()),
                ('results_end_at', models.DateTimeField()),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tick_rate', models.PositiveSmallIntegerField(default=20)),
                ('duration_ticks', models.PositiveIntegerField(default=0)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('events', models.JSONField(blank=True, default=list)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('round', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='race', to='racing.round')),
            ],
        ),
        migrations.CreateModel(
            name='RaceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.PositiveSmallIntegerField()),
                ('odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('finish_place', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('finish_tick', models.PositiveIntegerField(blank=True, null=True)),
                ('dnf_reason', models.CharField(blank=True, max_length=40)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='racing.race')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='race_entries', to='racing.racer')),
            ],
            options={
                'ordering': ['lane'],
                'constraints': [models.UniqueConstraint(fields=('race', 'racer'), name='racing_unique_racer'), models.UniqueConstraint(fields=('race', 'lane'), name='racing_unique_lane')],
            },
        ),
    ]
