# Generated by Django 5.2.16 on 2026-07-23 16:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=24)),
                ('color', models.CharField(default='#f6c453', max_length=7)),
                ('kind', models.CharField(choices=[('speed_tonic', 'Speed tonic'), ('guard_tonic', 'Guard tonic'), ('trip_tonic', 'Trip tonic'), ('confusion_tonic', 'Confusion tonic'), ('banana', 'Banana'), ('pothole', 'Pothole')], max_length=20)),
                ('target', models.CharField(choices=[('racer', 'Racer'), ('track', 'Track')], max_length=10)),
                ('price_cents', models.PositiveIntegerField()),
                ('effect_strength', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SpectatorSeatDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('color', models.CharField(default='#f6c453', max_length=7)),
                ('price_cents', models.PositiveIntegerField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='race',
            name='inputs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='racer',
            name='backstory',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='racer',
            name='tagline',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='max_round_item_spend_cents',
            field=models.PositiveBigIntegerField(default=2500),
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='max_round_item_uses',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='roomsettings',
            name='runner_count',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.CreateModel(
            name='RoundItemUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_lane', models.FloatField(blank=True, null=True)),
                ('track_position', models.FloatField(blank=True, null=True)),
                ('price_paid_cents', models.PositiveIntegerField()),
                ('client_request_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='racing.itemdefinition')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_uses', to='players.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_uses', to='racing.round')),
                ('target_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_uses', to='racing.raceentry')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('player', 'client_request_id'), name='racing_unique_item_player_request'), models.UniqueConstraint(fields=('player', 'round', 'item'), name='racing_unique_item_once_per_round')],
            },
        ),
        migrations.CreateModel(
            name='RoundSeatClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid_cents', models.PositiveIntegerField()),
                ('client_request_id', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_claims', to='players.player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_claims', to='racing.round')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='racing.spectatorseatdefinition')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('player', 'client_request_id'), name='racing_unique_seat_player_request'), models.UniqueConstraint(fields=('round', 'seat'), name='racing_unique_seat_per_round'), models.UniqueConstraint(fields=('player', 'round'), name='racing_unique_player_seat_per_round')],
            },
        ),
    ]
