# Generated by Django 5.2.16 on 2026-07-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0002_itemdefinition_spectatorseatdefinition_race_inputs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectatorseatdefinition',
            name='sprite_key',
            field=models.CharField(default='slime', max_length=40),
        ),
    ]
