# Generated by Django 5.2.16 on 2026-07-23 18:08

import django.core.validators
from django.db import migrations, models


def extend_legacy_race_limit(apps, schema_editor):
    room_settings = apps.get_model('racing', 'RoomSettings')
    room_settings.objects.filter(race_seconds=25).update(race_seconds=120)


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0003_spectatorseatdefinition_sprite_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomsettings',
            name='race_seconds',
            field=models.PositiveSmallIntegerField(default=120, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.RunPython(extend_legacy_race_limit, migrations.RunPython.noop),
    ]
