# Generated by Django 5.2.16 on 2026-07-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0004_alter_roomsettings_race_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdefinition',
            name='kind',
            field=models.CharField(choices=[('speed_tonic', 'Speed tonic'), ('guard_tonic', 'Guard tonic'), ('trip_tonic', 'Trip tonic'), ('confusion_tonic', 'Confusion tonic'), ('growth_tonic', 'Growth tonic'), ('shrink_tonic', 'Shrink tonic'), ('transform_tonic', 'Transform tonic'), ('banana', 'Banana'), ('pothole', 'Pothole')], max_length=20),
        ),
    ]
