# Generated by Django 5.2.16 on 2026-07-27 16:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def expand_item_use_cap(apps, _schema_editor):
    room_settings = apps.get_model("racing", "RoomSettings")
    room_settings.objects.filter(max_round_item_uses=3).update(max_round_item_uses=4)


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
        ('racing', '0005_alter_itemdefinition_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid_cents', models.PositiveIntegerField()),
                ('purchase_request_id', models.UUIDField(default=uuid.uuid4)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['purchased_at', 'pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='rounditemuse',
            name='racing_unique_item_once_per_round',
        ),
        migrations.AddField(
            model_name='roomsettings',
            name='max_inventory_items',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='roomsettings',
            name='max_round_item_uses',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.RunPython(expand_item_use_cap, migrations.RunPython.noop),
        migrations.AddField(
            model_name='inventoryitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='racing.itemdefinition'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='players.player'),
        ),
        migrations.AddField(
            model_name='rounditemuse',
            name='inventory_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='round_use', to='racing.inventoryitem'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['player', 'used_at'], name='racing_inve_player__34b970_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.UniqueConstraint(fields=('player', 'purchase_request_id'), name='racing_unique_inventory_purchase_request'),
        ),
    ]
