# Generated by Django 5.2.16 on 2026-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0006_inventoryitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rounditemuse',
            name='activation_tick',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemdefinition',
            name='kind',
            field=models.CharField(choices=[('speed_tonic', 'Speed tonic'), ('guard_tonic', 'Guard tonic'), ('trip_tonic', 'Trip tonic'), ('confusion_tonic', 'Confusion tonic'), ('growth_tonic', 'Growth tonic'), ('shrink_tonic', 'Shrink tonic'), ('transform_tonic', 'Transform tonic'), ('banana', 'Banana'), ('pothole', 'Pothole'), ('oil_slick', 'Oil slick'), ('boost_pad', 'Boost pad'), ('boxing_glove', 'Boxing glove')], max_length=20),
        ),
    ]
