# Generated by Django 5.2.16 on 2026-07-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0007_rounditemuse_activation_tick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='discarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
