# Generated by Django 5.2.16 on 2026-07-27 17:55

import django.core.validators
from django.db import migrations, models


def expand_item_budget(apps, _schema_editor):
    room_settings = apps.get_model("racing", "RoomSettings")
    room_settings.objects.filter(max_round_item_spend_cents=2_500).update(
        max_round_item_spend_cents=25_000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0008_inventoryitem_discarded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomsettings',
            name='max_round_stake_cents',
        ),
        migrations.AddField(
            model_name='spectatorseatdefinition',
            name='payout_bonus_bps',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='roomsettings',
            name='max_round_item_spend_cents',
            field=models.PositiveBigIntegerField(default=25000),
        ),
        migrations.RunPython(expand_item_budget, migrations.RunPython.noop),
    ]
