# Generated by Django 5.2.16 on 2026-07-27 21:31

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0004_player_balance_non_negative"),
        ("racing", "0010_roomsettings_max_round_stake_cents"),
    ]

    operations = [
        migrations.CreateModel(
            name="UpgradeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("inventory_capacity", "Inventory capacity"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "inventory_capacity",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                ("price_cents", models.PositiveIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="successors",
                        to="racing.upgradedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="PlayerUpgrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_paid_cents", models.PositiveIntegerField()),
                ("purchase_request_id", models.UUIDField(default=uuid.uuid4)),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upgrades",
                        to="players.player",
                    ),
                ),
                (
                    "upgrade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="racing.upgradedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["purchased_at", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="playerupgrade",
            constraint=models.UniqueConstraint(
                fields=("player", "upgrade"),
                name="racing_unique_player_upgrade",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerupgrade",
            constraint=models.UniqueConstraint(
                fields=("player", "purchase_request_id"),
                name="racing_unique_upgrade_purchase_request",
            ),
        ),
    ]
