# Generated by Django 5.2.16 on 2026-07-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0015_race_replay_montage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacerWorldRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('fastest_finish', 'Fastest official finish'), ('most_falls', 'Most falls in one race'), ('longest_crawl', 'Longest crawl in one race'), ('most_wrong_way', 'Most wrong-way episodes'), ('most_recoveries', 'Most recoveries'), ('most_showboats', 'Most showboats')], max_length=24, unique=True)),
                ('value', models.PositiveBigIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('race_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='world_records', to='racing.raceentry')),
                ('racer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='world_records', to='racing.racer')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='world_records', to='racing.round')),
            ],
            options={
                'ordering': ['metric'],
                'constraints': [models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='racing_world_record_positive_value')],
            },
        ),
    ]
