# Generated by Django 5.2.16 on 2026-07-29 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0021_round_broadcast_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_pct', models.PositiveIntegerField(help_text='Discount percentage (20-90).')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_discounts', to='racing.itemdefinition')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='racing.round')),
            ],
            options={
                'ordering': ['item__sort_order', 'item__name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('round', 'item'), name='racing_unique_round_discount')],
            },
        ),
    ]
