# Generated by Django 5.2.16 on 2026-07-29 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racing', '0022_round_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rounddiscount',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='round_discounts', to='racing.itemdefinition'),
        ),
    ]
