# Generated by Django 5.2.16 on 2026-07-23 16:17

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('racing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_request_id', models.UUIDField(default=uuid.uuid4)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('decimal_odds', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('void', 'Void')], default='pending', max_length=10)),
                ('payout_cents', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='players.player')),
                ('race_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='racing.raceentry')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='racing.round')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opening', 'Opening balance'), ('stake', 'Bet stake'), ('payout', 'Winning payout'), ('refund', 'Refund'), ('adjustment', 'Admin adjustment')], max_length=12)),
                ('amount_cents', models.BigIntegerField()),
                ('balance_after_cents', models.BigIntegerField()),
                ('description', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='betting.bet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='players.player')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='racing.round')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='bet',
            index=models.Index(fields=['round', 'status'], name='betting_bet_round_i_2664bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.UniqueConstraint(fields=('player', 'client_request_id'), name='betting_unique_player_request'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='betting_positive_stake'),
        ),
        migrations.AddConstraint(
            model_name='bet',
            constraint=models.CheckConstraint(condition=models.Q(('decimal_odds__gte', Decimal('1.01'))), name='betting_valid_odds'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['player', 'created_at'], name='betting_led_player__32c0ba_idx'),
        ),
    ]
