# Generated by Django 5.2.16 on 2026-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('stake', 'Bet stake'), ('payout', 'Winning payout'), ('refund', 'Refund'), ('adjustment', 'Admin adjustment'), ('item', 'Item purchase'), ('seat', 'Seat claim')], max_length=12),
        ),
    ]
