# Generated by Django 5.2.16 on 2026-07-27 21:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_alter_ledgerentry_kind'),
        ('players', '0004_player_balance_non_negative'),
        ('racing', '0010_roomsettings_max_round_stake_cents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('opening', 'Opening balance'), ('stake', 'Bet stake'), ('payout', 'Winning payout'), ('refund', 'Refund'), ('adjustment', 'Admin adjustment'), ('item', 'Item purchase'), ('seat', 'Seat claim'), ('bailout', 'Track medic bailout')], max_length=12),
        ),
        migrations.CreateModel(
            name='BailoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_request_id', models.UUIDField(default=uuid.uuid4)),
                ('wound_count', models.PositiveSmallIntegerField()),
                ('wounds', models.JSONField()),
                ('reward_credited', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailout_sessions', to='players.player')),
                ('race_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bailout_sessions', to='racing.raceentry')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bailout_sessions', to='racing.round')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='BailoutPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_index', models.PositiveSmallIntegerField()),
                ('patch_request_id', models.UUIDField(default=uuid.uuid4)),
                ('patched_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patches', to='betting.bailoutsession')),
            ],
            options={
                'ordering': ['patched_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='bailoutsession',
            index=models.Index(fields=['round', 'player'], name='betting_bai_round_i_4d97f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='bailoutsession',
            constraint=models.UniqueConstraint(fields=('player', 'round'), name='betting_unique_bailout_player_round'),
        ),
        migrations.AddConstraint(
            model_name='bailoutsession',
            constraint=models.UniqueConstraint(fields=('player', 'start_request_id'), name='betting_unique_bailout_start_request'),
        ),
        migrations.AddConstraint(
            model_name='bailoutsession',
            constraint=models.CheckConstraint(condition=models.Q(('wound_count__gte', 2), ('wound_count__lte', 5)), name='betting_bailout_wound_count_bounds'),
        ),
        migrations.AddConstraint(
            model_name='bailoutpatch',
            constraint=models.UniqueConstraint(fields=('session', 'wound_index'), name='betting_unique_bailout_wound_index'),
        ),
        migrations.AddConstraint(
            model_name='bailoutpatch',
            constraint=models.UniqueConstraint(fields=('session', 'patch_request_id'), name='betting_unique_bailout_patch_request'),
        ),
    ]
