# Generated by Django 5.2.16 on 2026-07-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betting", "0003_bailout_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="kind",
            field=models.CharField(
                choices=[
                    ("opening", "Opening balance"),
                    ("stake", "Bet stake"),
                    ("payout", "Winning payout"),
                    ("refund", "Refund"),
                    ("adjustment", "Admin adjustment"),
                    ("item", "Item purchase"),
                    ("seat", "Seat claim"),
                    ("bailout", "Track medic bailout"),
                    ("upgrade", "Permanent upgrade"),
                ],
                max_length=12,
            ),
        ),
    ]
