# Generated by Django 5.2.16 on 2026-07-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar_recipe',
            field=models.JSONField(default=dict),
        ),
    ]
