# Generated by Django 5.2.16 on 2026-07-27 19:29

import django.db.models.deletion
from django.db import migrations, models


def copy_player_devices(apps, schema_editor):
    Player = apps.get_model("players", "Player")
    Device = apps.get_model("players", "Device")
    for player in Player.objects.all().only("pk", "device_id").iterator():
        Device.objects.filter(pk=player.device_id).update(player_id=player.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_avatar_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="players.player",
            ),
        ),
        migrations.RunPython(copy_player_devices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="player",
            name="device",
        ),
    ]
